<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AForge.Imaging" Version="2.2.5" />
    <PackageReference Include="AForge.Math" Version="2.2.5" />
    <PackageReference Include="AForge.Vision" Version="2.2.5" />
    <PackageReference Include="Blast.Module" Version="0.0.1.4" />
  </ItemGroup>

</Project>
